### PR TITLE
Added RFCOMM, VHCI, slcan drivers

### PR DESCRIPTION
**Pull request by yesimxev**

### CODE REVIEW

**Comment by emman90ma** [comment]
Hello, can you add more features? I'm using the kernel with my mi 9t phone

**Comment by yesimxev** [comment]
> Hello, can you add more features? I'm using the kernel with my mi 9t phone

Just pushed new updates

**Comment by emman90ma** [comment]
hello does it support rtl8811cu chipset?

**Comment by emman90ma** [comment]
any new updates?

**Comment by emman90ma** [comment]
Is it possible to add rtl8811cu driver in the kernel?

**Comment by emman90ma** [comment]
hello any new updates? I am Mi 9T users thank you for your updates

**Pull request merged**
